"""Saturday HQ package."""

from saturday_hq.config import (
    DISCLAIMER_CFP,
    DISCLAIMER_MARKET,
    ENVIRONMENTS,
    HISTORICAL_DOMAINS,
    INGEST_MODES,
    MARKET_DOMAINS,
    RAW_CATALOG,
    SEASON_STATIC_DOMAINS,
    STATIC_DOMAINS,
    WEEKLY_DOMAINS,
    SaturdayHQConfig,
    catalog_for_env,
    current_cfb_season,
    current_env,
    current_ingest_mode,
    in_season,
    season_types_for,
)

__all__ = [
    "DISCLAIMER_CFP",
    "DISCLAIMER_MARKET",
    "ENVIRONMENTS",
    "HISTORICAL_DOMAINS",
    "INGEST_MODES",
    "MARKET_DOMAINS",
    "RAW_CATALOG",
    "SEASON_STATIC_DOMAINS",
    "STATIC_DOMAINS",
    "WEEKLY_DOMAINS",
    "SaturdayHQConfig",
    "catalog_for_env",
    "current_cfb_season",
    "current_env",
    "current_ingest_mode",
    "in_season",
    "season_types_for",
]
