command: ["npm", "run", "start"]

env:
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: SATURDAY_HQ_CATALOG
    value: cfb_saturday_hq_prod
  - name: SATURDAY_HQ_GOLD_SCHEMA
    value: cfb_gold
  - name: SATURDAY_HQ_APP_SCHEMA
    value: cfb_app
  - name: GENIE_SPACE_ID
    value: "01f18c7f92fa18cbbdb18f2248cbec37"
